# Generated by Django 4.2 on 2025-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
