# Generated by Django 5.2.6 on 2025-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_phone_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
